export const FETCH_REPOS_START= 'FETCH_REPOS_START';
export const FETCH_REPOS_SUCCESS= 'FETCH_REPOS_SUCCESS';
export const FETCH_REPOS_FAIL= 'FETCH_REPOS_FAIL';

export const FETCH_COMMITS_START= 'FETCH_COMMITS_START';
export const FETCH_COMMITS_SUCCESS= 'FETCH_COMMITS_SUCCESS';
export const FETCH_COMMITS_FAIL= 'FETCH_COMMITS_FAIL';

export const GITHUB_DATA_CLEANUP= 'GITHUB_DATA_CLEANUP';

export const FETCH_ERROR_CLEANESE = 'FETCH_ERROR_CLEANESE';